-- VIZO — seed local (solo datos DEMO)
--
-- Se ejecuta después de las migraciones en cada `supabase db reset`.
--
-- EL CATÁLOGO REGULATORIO NO VIVE AQUÍ. Está en la migración
-- 20260806190057_seed_catalogo_regulatorio.sql, porque es dato de PRODUCCIÓN:
-- sin él el motor no puede evaluar nada, así que tiene que existir en el
-- proyecto remoto, no solo en la máquina de quien desarrolla.
--
-- Este archivo es para los datos demo que ejercitan los casos de
-- docs/PRUEBAS.md: un tenant ficticio con sus sucursales, usuarios y clientes.
-- Nunca datos de un cliente real.
--
-- Vacío hasta la semana 5, cuando exista el alta de clientes en la UI. Por
-- ahora tests/estructura/smoke.sql crea los suyos y los deja limpios.
