-- ---------------------------------------------------------------------------
-- Un valor nuevo en tipo_alerta: la desviación del Perfil transaccional
-- ---------------------------------------------------------------------------
-- Art. 23 Ter 2 del Acuerdo 115/2026 (DOF 7-ago-2026, edición vespertina,
-- código 5795797), exigible el 1 de marzo de 2027 (Transitorio Cuarto):
--
--   «deberán tener e implementar un sistema de alertas que permita el
--    seguimiento y, en su caso, la detección oportuna de algún CAMBIO EN EL
--    COMPORTAMIENTO O PERFIL TRANSACCIONAL del Cliente o Usuaria»
--
-- El enum nació el 6 de agosto de 2026 con cinco valores —`proximidad`,
-- `aviso_requerido`, `revision_identidad`, `screening`, `calendario`— y
-- ninguno nombra esto. Se detectó al contrastar el capítulo
-- (`docs/RIESGO-EBR.md` §5) y no al construirlo.
--
-- POR QUÉ ESTE ARCHIVO ESTÁ SOLO, con una sola línea de efecto.
--
-- Postgres prohíbe USAR un valor de enum en la misma transacción en que se
-- agregó. La migración que sigue trae aserciones que insertan una alerta de
-- este tipo —son las que prueban que el sistema de alertas existe—, y no
-- podrían correr si el valor naciera ahí. La migración de la estructura del
-- obligado esquivó lo mismo comparando como texto en triggers; aquí no se
-- puede, porque la aserción escribe la fila.
alter type tipo_alerta add value if not exists 'desviacion_perfil';

-- Y un segundo valor, que NO es el mismo hecho aunque se parezca en pantalla.
--
-- «El cliente operó y nadie asentó lo que declaró» no es una desviación: no hay
-- perfil del cual desviarse. Es el hueco del Art. 23 Ter 1 ¶2, y lo que hay que
-- hacer con él —recabar la declaración— no se parece a lo que hay que hacer con
-- una desviación —mirar la operación—. Meterlos en el mismo valor obligaría a
-- que `alertas.perfil_id` fuera opcional para los dos, y entonces una
-- desviación sin perfil también pasaría: se perdería la única comprobación que
-- garantiza que la alerta pueda decir contra qué se desvió.
alter type tipo_alerta add value if not exists 'perfil_ausente';
