-- VIZO · Catálogos de valores del SAT (Capa 0)
--
-- POR QUÉ EXISTEN: el XSD de Fr. V Bis no tiene ni una sola `enumeration`.
-- Valida la FORMA (\d{1,2}) pero no el VALOR: un XML puede validar contra el
-- XSD y traer un tipo de desarrollo que no existe. Estos catálogos permiten
-- validar ANTES de generar, en vez de enterarse cuando el portal rechace el
-- aviso.
--
-- FUENTE: hoja "Combos" de la plantilla oficial DesarrollosInmobiliarios_v4_9.xlsm,
-- descargada del SPPLD el 4 de agosto de 2026. Copia auditable en
-- regulatorio/catalogos/din_catalogos.json.
--
-- NO se cargan los códigos postales ni las colonias (139,719 filas de la misma
-- hoja): el CP se valida por patrón y la colonia es texto libre en el XSD.
--
-- Versionados por vigencia igual que todo lo regulatorio: cuando las RCG
-- cambien un catálogo, se cierra la vigencia y se insertan filas nuevas.

create table catalogos_sat (
  id            uuid primary key default gen_random_uuid(),
  actividad_id  uuid references actividades_vulnerables(id),  -- NULL = todas
  catalogo      text not null,      -- 'tipo_desarrollo', 'moneda', ...
  codigo        text not null,
  descripcion   text not null,
  vigente_desde date not null,
  vigente_hasta date,
  created_at    timestamptz not null default now(),
  constraint catalogo_vigencia_coherente
    check (vigente_hasta is null or vigente_hasta >= vigente_desde),
  constraint catalogo_codigo_sin_traslape
    exclude using gist (
      (coalesce(actividad_id, '00000000-0000-0000-0000-000000000000'::uuid)) with =,
      catalogo with =, codigo with =,
      daterange(vigente_desde, vigente_hasta, '[]') with &&
    )
);

create index on catalogos_sat (catalogo, vigente_desde);

comment on table catalogos_sat is
  'Valores cerrados que el XSD no impone. Validar contra el XSD es necesario pero no suficiente.';

alter table catalogos_sat enable row level security;
create policy "catálogo legible" on catalogos_sat
  for select to authenticated using (true);
grant select on catalogos_sat to authenticated;

-- Consultas canónicas "as of", igual que el resto de la Capa 0.
create or replace function app.catalogo_vigente(p_catalogo text, p_fecha date)
returns table (codigo text, descripcion text)
language sql stable set search_path = '' as $$
  select c.codigo, c.descripcion
  from public.catalogos_sat c
  where c.catalogo = p_catalogo
    and daterange(c.vigente_desde, c.vigente_hasta, '[]') @> p_fecha
  order by length(c.codigo), c.codigo;
$$;

create or replace function app.codigo_valido(p_catalogo text, p_codigo text, p_fecha date)
returns boolean
language sql stable set search_path = '' as $$
  select exists (
    select 1 from public.catalogos_sat c
    where c.catalogo = p_catalogo and c.codigo = p_codigo
      and daterange(c.vigente_desde, c.vigente_hasta, '[]') @> p_fecha
  );
$$;

-- ---------------------------------------------------------------------------
-- Carga. vigente_desde = 2025-07-17, entrada en vigor de la reforma, igual
-- que el resto del catálogo regulatorio.
-- ---------------------------------------------------------------------------
with a as (select id from actividades_vulnerables where fraccion = 'V_BIS')
insert into catalogos_sat (actividad_id, catalogo, codigo, descripcion, vigente_desde)
select a.id, v.catalogo, v.codigo, v.descripcion, '2025-07-17'::date
from a, (values
  ('tipo_operacion', '1601', 'Aportación a Desarrollo(s) Inmobiliario(s)'),
  ('tipo_alerta', '100', 'Sin alerta.'),
  ('tipo_alerta', '3901', 'La(s) persona(s) que participa(n) en la operación se rehúsa(n) a proporcionar documentos personales que lo(s) identifiquen.'),
  ('tipo_alerta', '3902', 'El pago en preventa por el inmueble es realizado por un tercero sin relación aparente con el cliente.'),
  ('tipo_alerta', '3903', 'La(s) persona(s) que participa(n) en la operación realiza(n) múltiples aportaciones en un periodo muy corto de tiempo sin razón aparente.'),
  ('tipo_alerta', '3904', 'El cliente de la preventa no muestra tener interés en las características de la propiedad objeto de la operación, o en el precio y condiciones de la transacción.'),
  ('tipo_alerta', '3905', 'De acuerdo con medios informativos u otras fuentes de información pública, se tiene conocimiento o sospecha de que el cliente, un familiar o persona relacionada, está vinculado con actividades ilícitas o se encuentra bajo proceso de investigación.'),
  ('tipo_alerta', '3906', 'La(s) persona(s) que participa(n) en la operación no quiere(n) ser relacionada(s) con el desarrollo del inmueble.'),
  ('tipo_alerta', '3907', 'La operación no es acorde con la actividad económica o giro mercantil declarado por la(s) persona(s) que participa(n) en la operación.'),
  ('tipo_alerta', '3908', 'Hay indicios, o certeza, que las partes no están actuando en nombre propio y están tratando de ocultar la identidad de quien aporta los recursos.'),
  ('tipo_alerta', '3909', 'Uso de divisas en efectivo sin justificación alguna.'),
  ('tipo_alerta', '3910', 'Se conoce que las aportaciones se realizan por medio de transferencia(s) proveniente(s) de un país extranjero.'),
  ('tipo_alerta', '3911', 'La(s) persona(s) que participa(n) en la operación insiste(n) en realizar sus aportaciones en efectivo por montos elevados.'),
  ('tipo_alerta', '3912', 'La información y documentación presentada por la(s) persona(s) que participa(n) en la operación es inconsistente o de difícil verificación por parte del Sujeto Obligado.'),
  ('tipo_alerta', '3913', 'La(s) persona(s) que participa(n) en la operación intenta(n) sobornar, extorsionar o amenaza(n) con el fin de realizar la operación fuera de los parámetros establecidos, o con la finalidad de evitar el envío del Aviso.'),
  ('tipo_alerta', '9999', 'Otra alerta.'),
  ('pais', 'AF', 'AFGANISTAN'),
  ('pais', 'AL', 'ALBANIA'),
  ('pais', 'DE', 'ALEMANIA'),
  ('pais', 'AD', 'ANDORRA'),
  ('pais', 'AO', 'ANGOLA'),
  ('pais', 'AI', 'ANGUILA'),
  ('pais', 'AQ', 'ANTARTIDA'),
  ('pais', 'AG', 'ANTIGUA Y BARBUDA'),
  ('pais', 'AN', 'ANTILLAS NEERLANDESAS'),
  ('pais', 'SA', 'ARABIA SAUDI'),
  ('pais', 'DZ', 'ARGELIA'),
  ('pais', 'AR', 'ARGENTINA'),
  ('pais', 'AM', 'ARMENIA'),
  ('pais', 'AW', 'ARUBA'),
  ('pais', 'AU', 'AUSTRALIA'),
  ('pais', 'AT', 'AUSTRIA'),
  ('pais', 'AZ', 'AZERBAIYAN'),
  ('pais', 'BS', 'BAHAMAS'),
  ('pais', 'BH', 'BAHREIN'),
  ('pais', 'BD', 'BANGLADESH'),
  ('pais', 'BB', 'BARBADOS'),
  ('pais', 'BY', 'BELARUS'),
  ('pais', 'BE', 'BELGICA'),
  ('pais', 'BZ', 'BELICE'),
  ('pais', 'BJ', 'BENIN'),
  ('pais', 'BM', 'BERMUDAS'),
  ('pais', 'BT', 'BHUTAN'),
  ('pais', 'BO', 'BOLIVIA'),
  ('pais', 'BA', 'BOSNIA Y HERZEGOVINA'),
  ('pais', 'BW', 'BOTSUANA'),
  ('pais', 'BR', 'BRASIL'),
  ('pais', 'BN', 'BRUNEI'),
  ('pais', 'BG', 'BULGARIA'),
  ('pais', 'BF', 'BURKINA FASO'),
  ('pais', 'BI', 'BURUNDI'),
  ('pais', 'CV', 'CABO VERDE'),
  ('pais', 'KH', 'CAMBOYA'),
  ('pais', 'CM', 'CAMERUN'),
  ('pais', 'CA', 'CANADA'),
  ('pais', 'TD', 'CHAD'),
  ('pais', 'CZ', 'CHEQUIA'),
  ('pais', 'CL', 'CHILE'),
  ('pais', 'CN', 'CHINA'),
  ('pais', 'CY', 'CHIPRE'),
  ('pais', 'CP', 'CLIPPERTON'),
  ('pais', 'CO', 'COLOMBIA'),
  ('pais', 'KM', 'COMORAS'),
  ('pais', 'CG', 'CONGO'),
  ('pais', 'KP', 'COREA DEL NORTE'),
  ('pais', 'KR', 'COREA DEL SUR'),
  ('pais', 'CI', 'COSTA DE MARFIL'),
  ('pais', 'CR', 'COSTA RICA'),
  ('pais', 'HR', 'CROACIA'),
  ('pais', 'CU', 'CUBA'),
  ('pais', 'CW', 'CURAZAO'),
  ('pais', 'DK', 'DINAMARCA'),
  ('pais', 'DM', 'DOMINICA'),
  ('pais', 'EC', 'ECUADOR'),
  ('pais', 'EG', 'EGIPTO'),
  ('pais', 'SV', 'EL SALVADOR'),
  ('pais', 'AE', 'EMIRATOS ARABES UNIDOS'),
  ('pais', 'ER', 'ERITREA'),
  ('pais', 'SK', 'ESLOVAQUIA'),
  ('pais', 'SI', 'ESLOVENIA'),
  ('pais', 'ES', 'ESPAÑA'),
  ('pais', 'US', 'ESTADOS UNIDOS'),
  ('pais', 'EE', 'ESTONIA'),
  ('pais', 'ET', 'ETIOPIA'),
  ('pais', 'PH', 'FILIPINAS'),
  ('pais', 'FI', 'FINLANDIA'),
  ('pais', 'FJ', 'FIYI'),
  ('pais', 'FR', 'FRANCIA'),
  ('pais', 'GA', 'GABON'),
  ('pais', 'GM', 'GAMBIA'),
  ('pais', 'GE', 'GEORGIA'),
  ('pais', 'GS', 'GEORGIA DEL SUR E ISLAS SANDWICH DEL SUR'),
  ('pais', 'GH', 'GHANA'),
  ('pais', 'GI', 'GIBRALTAR'),
  ('pais', 'GD', 'GRANADA'),
  ('pais', 'EL', 'GRECIA'),
  ('pais', 'GL', 'GROENLANDIA'),
  ('pais', 'GP', 'GUADALUPE'),
  ('pais', 'GU', 'GUAM'),
  ('pais', 'GT', 'GUATEMALA'),
  ('pais', 'GF', 'GUAYANA FRANCESA'),
  ('pais', 'GG', 'GUERNESEY'),
  ('pais', 'GN', 'GUINEA'),
  ('pais', 'GQ', 'GUINEA ECUATORIAL'),
  ('pais', 'GW', 'GUINEA-BISSAU'),
  ('pais', 'GY', 'GUYANA'),
  ('pais', 'HT', 'HAITI'),
  ('pais', 'HN', 'HONDURAS'),
  ('pais', 'HK', 'HONG KONG'),
  ('pais', 'HU', 'HUNGRIA'),
  ('pais', 'IN', 'INDIA'),
  ('pais', 'ID', 'INDONESIA'),
  ('pais', 'IR', 'IRAN'),
  ('pais', 'IQ', 'IRAQ'),
  ('pais', 'IE', 'IRLANDA'),
  ('pais', 'BV', 'ISLA BOUVET'),
  ('pais', 'CX', 'ISLA CHRISTMAS'),
  ('pais', 'IM', 'ISLA DE MAN'),
  ('pais', 'NF', 'ISLA NORFOLK'),
  ('pais', 'IS', 'ISLANDIA'),
  ('pais', 'AX', 'ISLAS ÅLAND'),
  ('pais', 'KY', 'ISLAS CAIMAN'),
  ('pais', 'CC', 'ISLAS COCOS'),
  ('pais', 'CK', 'ISLAS COOK'),
  ('pais', 'FO', 'ISLAS FEROE'),
  ('pais', 'HM', 'ISLAS HEARD Y MCDONALD'),
  ('pais', 'FK', 'ISLAS MALVINAS'),
  ('pais', 'MP', 'ISLAS MARIANAS DEL NORTE'),
  ('pais', 'MH', 'ISLAS MARSHALL'),
  ('pais', 'UM', 'ISLAS MENORES ALEJADAS DE LOS ESTADOS UNIDOS'),
  ('pais', 'PN', 'ISLAS PITCAIRN'),
  ('pais', 'SB', 'ISLAS SALOMON'),
  ('pais', 'TC', 'ISLAS TURCAS Y CAICOS'),
  ('pais', 'VG', 'ISLAS VIRGENES BRITANICAS'),
  ('pais', 'VI', 'ISLAS VIRGENES DE LOS ESTADOS UNIDOS'),
  ('pais', 'IL', 'ISRAEL'),
  ('pais', 'IT', 'ITALIA'),
  ('pais', 'JM', 'JAMAICA'),
  ('pais', 'JP', 'JAPON'),
  ('pais', 'JE', 'JERSEY'),
  ('pais', 'JO', 'JORDANIA'),
  ('pais', 'KZ', 'KAZAJSTAN'),
  ('pais', 'KE', 'KENIA'),
  ('pais', 'KG', 'KIRGUISTAN'),
  ('pais', 'KI', 'KIRIBATI'),
  ('pais', 'XK', 'KOSOVO'),
  ('pais', 'KW', 'KUWAIT'),
  ('pais', 'LA', 'LAOS'),
  ('pais', 'LS', 'LESOTHO'),
  ('pais', 'LV', 'LETONIA'),
  ('pais', 'LB', 'LIBANO'),
  ('pais', 'LR', 'LIBERIA'),
  ('pais', 'LY', 'LIBIA'),
  ('pais', 'LI', 'LIECHTENSTEIN'),
  ('pais', 'LT', 'LITUANIA'),
  ('pais', 'LU', 'LUXEMBURGO'),
  ('pais', 'MO', 'MACAO'),
  ('pais', 'MK', 'MACEDONIA'),
  ('pais', 'MG', 'MADAGASCAR'),
  ('pais', 'MY', 'MALASIA'),
  ('pais', 'MW', 'MALAWI'),
  ('pais', 'MV', 'MALDIVAS'),
  ('pais', 'ML', 'MALI'),
  ('pais', 'MT', 'MALTA'),
  ('pais', 'MA', 'MARRUECOS'),
  ('pais', 'MQ', 'MARTINICA'),
  ('pais', 'MU', 'MAURICIO'),
  ('pais', 'MR', 'MAURITANIA'),
  ('pais', 'YT', 'MAYOTTE'),
  ('pais', 'MX', 'MEXICO'),
  ('pais', 'FM', 'MICRONESIA'),
  ('pais', 'MD', 'MOLDOVA'),
  ('pais', 'MC', 'MONACO'),
  ('pais', 'MN', 'MONGOLIA'),
  ('pais', 'ME', 'MONTENEGRO'),
  ('pais', 'MS', 'MONTSERRAT'),
  ('pais', 'MZ', 'MOZAMBIQUE'),
  ('pais', 'MM', 'MYANMAR'),
  ('pais', 'NA', 'NAMIBIA'),
  ('pais', 'NR', 'NAURU'),
  ('pais', 'NP', 'NEPAL'),
  ('pais', 'NI', 'NICARAGUA'),
  ('pais', 'NE', 'NIGER'),
  ('pais', 'NG', 'NIGERIA'),
  ('pais', 'NU', 'NIUE'),
  ('pais', 'NO', 'NORUEGA'),
  ('pais', 'NC', 'NUEVA CALEDONIA'),
  ('pais', 'NZ', 'NUEVA ZELANDA'),
  ('pais', 'OM', 'OMAN'),
  ('pais', 'NL', 'PAISES BAJOS'),
  ('pais', 'PK', 'PAKISTAN'),
  ('pais', 'PW', 'PALAOS'),
  ('pais', 'PA', 'PANAMA'),
  ('pais', 'PG', 'PAPUA NUEVA GUINEA'),
  ('pais', 'PY', 'PARAGUAY'),
  ('pais', 'PE', 'PERU'),
  ('pais', 'PF', 'POLINESIA FRANCESA'),
  ('pais', 'PL', 'POLONIA'),
  ('pais', 'PT', 'PORTUGAL'),
  ('pais', 'PR', 'PUERTO RICO'),
  ('pais', 'QA', 'QATAR'),
  ('pais', 'UK', 'REINO UNIDO'),
  ('pais', 'CF', 'REPUBLICA CENTROAFRICANA'),
  ('pais', 'CD', 'REPUBLICA DEMOCRATICA DEL CONGO'),
  ('pais', 'DO', 'REPUBLICA DOMINICANA'),
  ('pais', 'RE', 'REUNION'),
  ('pais', 'RW', 'RUANDA'),
  ('pais', 'RO', 'RUMANIA'),
  ('pais', 'RU', 'RUSIA'),
  ('pais', 'EH', 'SAHARA OCCIDENTAL'),
  ('pais', 'WS', 'SAMOA'),
  ('pais', 'AS', 'SAMOA AMERICANA'),
  ('pais', 'BL', 'SAN BARTOLOME'),
  ('pais', 'KN', 'SAN CRISTOBAL Y NIEVES'),
  ('pais', 'SM', 'SAN MARINO'),
  ('pais', 'MF', 'SAN MARTIN'),
  ('pais', 'PM', 'SAN PEDRO Y MIQUELON'),
  ('pais', 'VC', 'SAN VICENTE Y LAS GRANADINAS'),
  ('pais', 'SH', 'SANTA ELENA'),
  ('pais', 'LC', 'SANTA LUCIA'),
  ('pais', 'VA', 'SANTA SEDE / ESTADO DE LA CIUDAD DEL VATICANO'),
  ('pais', 'ST', 'SANTO TOME Y PRINCIPE'),
  ('pais', 'SN', 'SENEGAL'),
  ('pais', 'RS', 'SERBIA'),
  ('pais', 'SC', 'SEYCHELLES'),
  ('pais', 'SL', 'SIERRA LEONA'),
  ('pais', 'SG', 'SINGAPUR'),
  ('pais', 'SY', 'SIRIA'),
  ('pais', 'SO', 'SOMALIA'),
  ('pais', 'LK', 'SRI LANKA'),
  ('pais', 'SZ', 'SUAZILANDIA'),
  ('pais', 'ZA', 'SUDAFRICA'),
  ('pais', 'SD', 'SUDAN'),
  ('pais', 'SE', 'SUECIA'),
  ('pais', 'CH', 'SUIZA'),
  ('pais', 'SR', 'SURINAM'),
  ('pais', 'SJ', 'SVALBARD Y JAN MAYEN'),
  ('pais', 'TH', 'TAILANDIA'),
  ('pais', 'TW', 'TAIWAN'),
  ('pais', 'TZ', 'TANZANIA'),
  ('pais', 'TJ', 'TAYIKISTAN'),
  ('pais', 'IO', 'TERRITORIO BRITANICO DEL OCEANO INDICO'),
  ('pais', 'TF', 'TERRITORIOS AUSTRALES FRANCESES'),
  ('pais', 'PS', 'TERRITORIOS PALESTINOS'),
  ('pais', 'TL', 'TIMOR ORIENTAL'),
  ('pais', 'TG', 'TOGO'),
  ('pais', 'TK', 'TOKELAU'),
  ('pais', 'TO', 'TONGA'),
  ('pais', 'TT', 'TRINIDAD Y TOBAGO'),
  ('pais', 'TN', 'TUNEZ'),
  ('pais', 'TM', 'TURKMENISTAN'),
  ('pais', 'TR', 'TURQUIA'),
  ('pais', 'TV', 'TUVALU'),
  ('pais', 'UA', 'UCRANIA'),
  ('pais', 'UG', 'UGANDA'),
  ('pais', 'UY', 'URUGUAY'),
  ('pais', 'UZ', 'UZBEKISTAN'),
  ('pais', 'VU', 'VANUATU'),
  ('pais', 'VE', 'VENEZUELA'),
  ('pais', 'VN', 'VIETNAM'),
  ('pais', 'WF', 'WALLIS Y FUTUNA'),
  ('pais', 'YE', 'YEMEN'),
  ('pais', 'DJ', 'YIBUTI'),
  ('pais', 'ZM', 'ZAMBIA'),
  ('pais', 'ZW', 'ZIMBABUE'),
  ('entidad_federativa', '1', 'AGUASCALIENTES'),
  ('entidad_federativa', '2', 'BAJA CALIFORNIA'),
  ('entidad_federativa', '3', 'BAJA CALIFORNIA SUR'),
  ('entidad_federativa', '4', 'CAMPECHE'),
  ('entidad_federativa', '5', 'COAHUILA DE ZARAGOZA'),
  ('entidad_federativa', '6', 'COLIMA'),
  ('entidad_federativa', '7', 'CHIAPAS'),
  ('entidad_federativa', '8', 'CHIHUAHUA'),
  ('entidad_federativa', '9', 'DISTRITO FEDERAL'),
  ('entidad_federativa', '10', 'DURANGO'),
  ('entidad_federativa', '11', 'GUANAJUATO'),
  ('entidad_federativa', '12', 'GUERRERO'),
  ('entidad_federativa', '13', 'HIDALGO'),
  ('entidad_federativa', '14', 'JALISCO'),
  ('entidad_federativa', '15', 'MÉXICO'),
  ('entidad_federativa', '16', 'MICHOACÁN DE OCAMPO'),
  ('entidad_federativa', '17', 'MORELOS'),
  ('entidad_federativa', '18', 'NAYARIT'),
  ('entidad_federativa', '19', 'NUEVO LEÓN'),
  ('entidad_federativa', '20', 'OAXACA'),
  ('entidad_federativa', '21', 'PUEBLA'),
  ('entidad_federativa', '22', 'QUERÉTARO'),
  ('entidad_federativa', '23', 'QUINTANA ROO'),
  ('entidad_federativa', '24', 'SAN LUIS POTOSÍ'),
  ('entidad_federativa', '25', 'SINALOA'),
  ('entidad_federativa', '26', 'SONORA'),
  ('entidad_federativa', '27', 'TABASCO'),
  ('entidad_federativa', '28', 'TAMAULIPAS'),
  ('entidad_federativa', '29', 'TLAXCALA'),
  ('entidad_federativa', '30', 'VERACRUZ DE IGNACIO DE LA LLAVE'),
  ('entidad_federativa', '31', 'YUCATÁN'),
  ('entidad_federativa', '32', 'ZACATECAS'),
  ('actividad_economica', '1000000', 'NO APLICA'),
  ('actividad_economica', '1110100', 'AGRICULTURA Y SILVICULTURA - ADMINISTRADORES O TRABAJADORES AGRICOLAS'),
  ('actividad_economica', '1110400', 'AGRICULTURA Y SILVICULTURA - ADMINISTRADORES O TRABAJADORES SILVICOLAS Y FORESTALES'),
  ('actividad_economica', '1220100', 'GANADERIA - APICULTORES'),
  ('actividad_economica', '1220200', 'GANADERIA - ADMINISTRADORES, CRIADORES O SUPERVISORES AVICOLAS Y GANADEROS'),
  ('actividad_economica', '1330200', 'PESCA Y ACUACULTURA - PESCADORES Y TRABAJADORES EN LA CRIA Y CULTIVO DE ESPECIES MARINAS'),
  ('actividad_economica', '2130100', 'MINERIA, EXTRACCION Y SUMINISTRO - TECNICOS GEOLOGICOS Y DE MINERALES'),
  ('actividad_economica', '2140100', 'MINERIA, EXTRACCION Y SUMINISTRO - INGENIEROS, OPERADORES O AYUDANTES EN LA EXTRACCION Y REFINACION MINERA'),
  ('actividad_economica', '2210100', 'MINERIA, EXTRACCION Y SUMINISTRO - AYUDANTES EN LA PERFORACION DE POZOS DE PETROLEO Y GAS NATURAL'),
  ('actividad_economica', '2240200', 'MINERIA, EXTRACCION Y SUMINISTRO - INGENIEROS PETROLEROS'),
  ('actividad_economica', '2420100', 'MINERIA, EXTRACCION Y SUMINISTRO - OPERADORES DE CENTRALES O SISTEMAS  DE ENERGIA ELECTRICAS'),
  ('actividad_economica', '2420200', 'MINERIA, EXTRACCION Y SUMINISTRO - OPERADORES DE MAQUINAS DE VAPOR'),
  ('actividad_economica', '2530100', 'MINERIA, EXTRACCION Y SUMINISTRO - GERENTE, SUPERVISOR U OPERADORES DE  TRATAMIENTO Y POTABILIZACION, ABASTECIMIENTO Y RECOLECCION DE AGUA'),
  ('actividad_economica', '3130100', 'CONSTRUCCION - DECORADORES DE INTERIORES'),
  ('actividad_economica', '3130300', 'CONSTRUCCION -  INGENIEROS, TECNICOS Y OPERADORES DE LA CONSTRUCCION'),
  ('actividad_economica', '3310300', 'CONSTRUCCION - COLOCADORES DE PRODUCTOS PREFABRICADOS EN INMUEBLES'),
  ('actividad_economica', '3310400', 'CONSTRUCCION - PINTORES'),
  ('actividad_economica', '3310600', 'CONSTRUCCION - VIDRIEROS'),
  ('actividad_economica', '3410200', 'CONSTRUCCION - REPARADORES DE VIAS DE COMUNICACION'),
  ('actividad_economica', '3420100', 'CONSTRUCCION - PLOMEROS E INSTALADORES DE TUBERIA'),
  ('actividad_economica', '3420200', 'CONSTRUCCION - ARQUITECTOS'),
  ('actividad_economica', '4130300', 'MECANICA - MECANICOS DE EQUIPO PESADO'),
  ('actividad_economica', '4130500', 'MECANICA - INGENIERO O MECANICOS INSTALADORES DE MAQUINARIA INDUSTRIAL'),
  ('actividad_economica', '4131000', 'MECANICA - INGENIERO O TECNICO EN MECANICA DE VEHICULOS TERRESTRES, AEREOS Y ACUATICOS'),
  ('actividad_economica', '4230200', 'ELECTRICIDAD - INGENIEROS O TECNICOS ELECTRICISTAS'),
  ('actividad_economica', '4230500', 'ELECTRICIDAD - TECNICOS EN REFRIGERACION, AIRE ACONDICIONADO Y CALEFACCION'),
  ('actividad_economica', '4330100', 'ELECTRONICA - MECANICOS DE INSTRUMENTOS INDUSTRIALES'),
  ('actividad_economica', '4330200', 'ELECTRONICA - INGENIERO O TECNICOS EN  ELECTRONICA'),
  ('actividad_economica', '4430200', 'INFORMATICA - INGENIERO O TECNICOS PROGRAMADORES EN INFORMATICA'),
  ('actividad_economica', '4440100', 'INFORMATICA - PROFESIONISTAS O TECNICOS DE SISTEMAS DE INFORMACION Y PROCESAMIENTO DE DATOS'),
  ('actividad_economica', '4530200', 'TELECOMUNICACIONES - INGENIERO, INSTALADORES Y REPARADORES DE EQUIPOS Y ACCESORIOS DE TELECOMUNICACIONES'),
  ('actividad_economica', '4530500', 'TELECOMUNICACIONES - TELEGRAFISTAS Y RADIO-OPERADORES'),
  ('actividad_economica', '4630100', 'PROCESOS INDUSTRIALES - INGENIERO O TECNICOS INDUSTRIAL Y DE PRODUCCION'),
  ('actividad_economica', '4640300', 'PROCESOS INDUSTRIALES - INGENIEROS METALURGICOS Y DE MATERIALES'),
  ('actividad_economica', '5110100', 'MINERALES NO METALICOS - OPERADORES O TRABAJADORES DE VIDRIO Y CONCRETO'),
  ('actividad_economica', '5121300', 'MINERALES NO METALICOS - OPERADORES DE MAQUINAS PROCESADORAS DE MINERALES NO METALICOS'),
  ('actividad_economica', '5210100', 'METALES - SUPERVISORES U OPERADORES DE PROCESAMIENTO Y FUNDICION DE METALES'),
  ('actividad_economica', '5310700', 'ALIMENTOS Y BEBIDAS - TRABAJADORES EN LA ELABORACION  Y PROCESAMIENTO DE ALIMENTOS, BEBIDAS Y TABACO'),
  ('actividad_economica', '5410100', 'TEXTILES Y PRENDAS DE VESTIR - TRABAJADORES EN LA PRODUCCION DE TEXTILES, PRENDAS DE VESTIR Y CALZADO'),
  ('actividad_economica', '5420700', 'TEXTILES Y PRENDAS DE VESTIR - TRABAJADORES DE REPARACION DE PRENDAS DE VESTIR Y CALZADO'),
  ('actividad_economica', '5510100', 'MADERA, PAPEL, Y PIEL - TRABAJADORES EN LA FABRICACION DE MUEBLES O PRODUCTOS DE MADERA Y/O PIEL'),
  ('actividad_economica', '5610200', 'PRODUCTOS QUIMICOS - TRABAJADORES EN EL PROCESAMIENTO Y FABRICACION DE PRODUCTOS QUIMICOS Y FARMACOQUIMICAS'),
  ('actividad_economica', '5710200', 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - TRABAJADORES  EN LA FABRICACION DE PRODUCTOS METALICOS, DE HULE Y PLASTICOS'),
  ('actividad_economica', '5720800', 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - ENSAMBLADORES Y ACABADORES DE PRODUCTOS DE PLASTICO'),
  ('actividad_economica', '5720900', 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - FABRICANTES DE HERRAMIENTAS Y TROQUELES'),
  ('actividad_economica', '5721000', 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - HERREROS Y FORJADORES'),
  ('actividad_economica', '5721100', 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - JOYEROS Y ORFEBRES'),
  ('actividad_economica', '5722900', 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - SOLDADORES Y OXICORTADORES'),
  ('actividad_economica', '5730600', 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - TRABAJADORES EN EL ENSAMBLADO DE VEHICULOS, MOLDEADO, LAMINADO Y MONTAJE DE PIEZAS METALICAS, HULE O PLASTICO'),
  ('actividad_economica', '5731100', 'PRODUCTOS METALICOS Y DE HULE Y PLASTICO - SUPERVISORES EN LA FABRICACION Y MONTAJE DE ARTICULOS DEPORTIVOS, DE JUGUETES Y SIMILARES'),
  ('actividad_economica', '5810200', 'PRODUCTOS ELECTRICOS Y ELECTRONICOS - TRABAJADORES EN LA FABRICACION DE PRODUCTOS ELECTRICOS Y ELECTRONICOS'),
  ('actividad_economica', '5910400', 'PRODUCTOS IMPRESOS - TRABAJADORES EN LA ELABORACION DE PRODUCTOS IMPRESOS'),
  ('actividad_economica', '6120100', 'TRANSPORTE FERROVIARIO - CONDUCTORES Y OPERADORES DE TREN SUBTERRANEO Y DE TREN LIGERO'),
  ('actividad_economica', '6120200', 'TRANSPORTE FERROVIARIO - TRABAJADORES DE FERROCARRILES'),
  ('actividad_economica', '6220100', 'TRANSPORTE TERRESTRE - CONDUCTORES DE VEHICULOS DE TRANSPORTE, SERVICIOS DE CARGA Y/O REPARTO'),
  ('actividad_economica', '6330100', 'TRANSPORTE AEREO - COORDINADORES Y SUPERVISORES EN SERVICIOS DE TRANSPORTE AEREO'),
  ('actividad_economica', '6330200', 'TRANSPORTE AEREO - DESPACHADORES DE VUELO Y ESPECIALISTAS EN SERVICIOS AEREOS'),
  ('actividad_economica', '6330400', 'TRANSPORTE AEREO - SUPERVISORES DE SISTEMAS DE COMUNICACION PARA LA AERONAVEGACION'),
  ('actividad_economica', '6330500', 'TRANSPORTE AEREO - PILOTOS DE AVIACION E INSTRUCTORES DE VUELO'),
  ('actividad_economica', '6330600', 'TRANSPORTE AEREO - SOBRECARGOS'),
  ('actividad_economica', '6420100', 'TRANSPORTE MARITIMO Y FLUVIAL - CONDUCTORES DE EMBARCACIONES'),
  ('actividad_economica', '6430100', 'TRANSPORTE MARITIMO Y FLUVIAL - JEFES Y CONTROLADORES DE TRAFICO MARITIMO'),
  ('actividad_economica', '6430300', 'TRANSPORTE MARITIMO Y FLUVIAL - PILOTOS, CAPITANES DE PUERTOS Y OFICIALES DE CUBIERTA'),
  ('actividad_economica', '7110200', 'COMERCIO - DESPACHADORES DE GASOLINERA'),
  ('actividad_economica', '7110300', 'COMERCIO - EMPACADORES DE MERCANCIAS'),
  ('actividad_economica', '7110500', 'COMERCIO - TAQUILLEROS'),
  ('actividad_economica', '7110600', 'COMERCIO - VENDEDORES AMBULANTES'),
  ('actividad_economica', '7120100', 'COMERCIO - CAJEROS REGISTRADORES'),
  ('actividad_economica', '7130200', 'COMERCIO - REPRESENTANTES DE VENTAS POR TELEFONO O POR TELEVISION'),
  ('actividad_economica', '7130400', 'COMERCIO - VENDEDORES ESPECIALIZADOS'),
  ('actividad_economica', '7140100', 'COMERCIO - GERENTES O SUPERVISOR DE ESTABLECIMIENTO COMERCIAL'),
  ('actividad_economica', '7140200', 'COMERCIO - GERENTES O EMPLEADOS DE VENTAS'),
  ('actividad_economica', '7210100', 'ALIMENTACION Y HOSPEDAJE - TRABAJADORES DE SERVICIO DE ALIMENTOS Y BEBIDAS'),
  ('actividad_economica', '7230200', 'ALIMENTACION Y HOSPEDAJE - JEFES DE COCINA, RESTAURANTE Y/O BAR'),
  ('actividad_economica', '7240200', 'ALIMENTACION Y HOSPEDAJE - TRABAJADORES DE SERVICIOS DE ALOJAMIENTO'),
  ('actividad_economica', '7330200', 'TURISMO - COORDINADORES DE OPERACIONES EN AGENCIAS DE VIAJES'),
  ('actividad_economica', '7330300', 'TURISMO - GUIAS DE EXCURSIONES O ECOTURISTICO'),
  ('actividad_economica', '7430100', 'DEPORTE Y ESPARCIMIENTO - ANIMADORES RECREATIVOS'),
  ('actividad_economica', '7430200', 'DEPORTE Y ESPARCIMIENTO - ATLETAS, ENTRENADORES O INSTRUCTORES EN DEPORTE Y RECREACION'),
  ('actividad_economica', '7430400', 'DEPORTE Y ESPARCIMIENTO - OFICIALES, JUECES Y ARBITROS DEPORTIVOS'),
  ('actividad_economica', '7530100', 'SERVICIOS PERSONALES - ESTILISTAS, ESTETICISTAS Y MASAJISTAS'),
  ('actividad_economica', '7540100', 'SERVICIOS PERSONALES - TRBAJADORES DE SERVICIOS FUNERARIOS O CEMENTERIOS'),
  ('actividad_economica', '7620100', 'REPARACION DE ARTICULOS DE USO DOMESTICO Y PERSONAL - CERRAJEROS'),
  ('actividad_economica', '7620200', 'REPARACION DE ARTICULOS DE USO DOMESTICO Y PERSONAL - REPARADORES DE ARTICULOS DE HULE'),
  ('actividad_economica', '7630100', 'REPARACION DE ARTICULOS DE USO DOMESTICO Y PERSONAL - RELOJEROS Y REPARADORES DE RELOJES'),
  ('actividad_economica', '7630200', 'REPARACION DE ARTICULOS DE USO DOMESTICO Y PERSONAL - REPARADORES DE APARATOS ELECTRICOS'),
  ('actividad_economica', '7720100', 'LIMPIEZA - SERVICIOS DE CAMARISTAS Y ASEADORES'),
  ('actividad_economica', '7720200', 'LIMPIEZA - TRABAJADORES DE TINTORERIA Y LAVANDERIA'),
  ('actividad_economica', '7720300', 'LIMPIEZA - FUMIGADORES DE PLAGAS'),
  ('actividad_economica', '7810200', 'SERVICIO POSTAL Y MENSAJERIA - EMPLEADOS DE SERVICIOS DE MENSAJERIA'),
  ('actividad_economica', '8120100', 'BOLSA, BANCA Y SEGUROS - GERENTES O TRABAJADORES DE SERVICIOS Y PRODUCTOS FINANCIEROS'),
  ('actividad_economica', '8130500', 'BOLSA, BANCA Y SEGUROS - VALUADORES'),
  ('actividad_economica', '8140100', 'BOLSA, BANCA Y SEGUROS - AGENTES DE VALORES, PROMOTORES Y CORREDORES DE INVERSION'),
  ('actividad_economica', '8210100', 'ADMINISTRACION - TRABAJADORES DE ARCHIVO, ALMACEN DE INVENTARIOS'),
  ('actividad_economica', '8220400', 'ADMINISTRACION - CAPTURISTA Y OPERADORES DE TELEFONO'),
  ('actividad_economica', '8220600', 'ADMINISTRACION - PAGADORES Y COBRADORES'),
  ('actividad_economica', '8230300', 'ADMINISTRACION - DIRECTORES, GERENTES  Y EMPLEADOS DE COMPRAS, FINANZAS, RECURSOS HUMANOS Y SERVICIOS ADMINISTRATIVOS'),
  ('actividad_economica', '8240100', 'ADMINISTRACION - ASISTENTES ADMINISTRATIVOS'),
  ('actividad_economica', '8240200', 'ADMINISTRACION - CONTADORES Y AUDITORES'),
  ('actividad_economica', '8240600', 'ADMINISTRACION - DIRECTORES, GERENTES Y EMPLEADOS DE PRODUCCION'),
  ('actividad_economica', '8240700', 'ADMINISTRACION - DIRECTORES, GERENTES Y EMPLEADOS DE SERVICIOS DE TRANSPORTE'),
  ('actividad_economica', '8250100', 'ADMINISTRACION - CONSULTORES'),
  ('actividad_economica', '8250200', 'ADMINISTRACION - DIRECTORES, GERENTES Y EMPLEADOS DE COMERCIALIZACION'),
  ('actividad_economica', '8250800', 'ADMINISTRACION - DIRECTORES, GERENTES Y EMPELADOS ADMINISTRATIVOS'),
  ('actividad_economica', '8340100', 'SERVICIOS LEGALES - ABOGADOS Y ASESORES LEGALES'),
  ('actividad_economica', '8340300', 'SERVICIOS LEGALES - NOTARIOS Y CORREDORES PUBLICOS'),
  ('actividad_economica', '9120700', 'SERVICIOS MEDICOS - ENFERMERAS Y/O PARAMEDICOS'),
  ('actividad_economica', '9130300', 'SERVICIOS MEDICOS - DIETISTAS Y NUTRIOLOGOS'),
  ('actividad_economica', '9131200', 'SERVICIOS MEDICOS - TECNICOS DE LABORATORIO MEDICO'),
  ('actividad_economica', '9140200', 'SERVICIOS MEDICOS - DIRECTORES DE INSTITUCIONES EN EL CUIDADO DE LA SALUD'),
  ('actividad_economica', '9140400', 'SERVICIOS MEDICOS - FARMACEUTICOS'),
  ('actividad_economica', '9140500', 'SERVICIOS MEDICOS - FISIOTERAPEUTAS Y QUIROPRACTICOS'),
  ('actividad_economica', '9140700', 'SERVICIOS MEDICOS - MEDICOS ESPECIALISTAS'),
  ('actividad_economica', '9140800', 'SERVICIOS MEDICOS - MEDICOS GENERALES Y FAMILIARES'),
  ('actividad_economica', '9230100', 'INSPECCION - INSPECTORES DE SALUD AMBIENTAL, SANIDAD Y DEL TRABAJO'),
  ('actividad_economica', '9230200', 'INSPECCION - INSPECTORES DE TRANSPORTE DE CARGA Y DE PASAJEROS'),
  ('actividad_economica', '9230300', 'INSPECCION - INSPECTORES FISCALES Y DE PRECIOS'),
  ('actividad_economica', '9230400', 'INSPECCION - INSPECTORES SANITARIOS Y DE CONTROL DE CALIDAD DE PRODUCTOS CARNICOS, PESQUEROS Y AGRICOLAS'),
  ('actividad_economica', '9330100', 'SEGURIDAD SOCIAL - CONSEJEROS DE EMPLEO'),
  ('actividad_economica', '9330300', 'SEGURIDAD SOCIAL - TRABAJADORES DE SERVICIO SOCIAL Y DE LA COMUNIDAD'),
  ('actividad_economica', '9420100', 'PROTECCION DE BIENES Y/O PERSONAS - BOMBEROS'),
  ('actividad_economica', '9420300', 'PROTECCION DE BIENES Y/O PERSONAS - GUARDIAS DE SEGURIDAD'),
  ('actividad_economica', '9430100', 'PROTECCION DE BIENES Y/O PERSONAS - DETECTIVES PRIVADOS'),
  ('actividad_economica', '1014010', 'RADIO, CINE, TELEVISION Y TEATRO - DISEÑADORES GRAFICOS'),
  ('actividad_economica', '1014030', 'RADIO, CINE, TELEVISION Y TEATRO - EDITORES, PERIODISTAS, REPORTEROS Y REDACTORES'),
  ('actividad_economica', '1023010', 'RADIO, CINE, TELEVISION Y TEATRO - ASISTENTES Y/U OPERADORES DE PRODUCCION DE CINE, RADIO Y TELEVISION'),
  ('actividad_economica', '1023070', 'RADIO, CINE, TELEVISION Y TEATRO - LOCUTORES, COMENTARISTAS Y CRONISTAS DE RADIO Y TELEVISION'),
  ('actividad_economica', '1024020', 'RADIO, CINE, TELEVISION Y TEATRO - PRODUCTORES Y DIRECTORES DE CINE, TELEVISION Y TEATRO'),
  ('actividad_economica', '1033010', 'INTERPRETACION ARTISTICA - ACTORES, BAILARINES, MUSICOS, ESCRITORES'),
  ('actividad_economica', '1033020', 'INTERPRETACION ARTISTICA - ARTESANOS'),
  ('actividad_economica', '1033040', 'INTERPRETACION ARTISTICA - FOTOGRAFOS'),
  ('actividad_economica', '1034010', 'INTERPRETACION ARTISTICA - ARTISTAS PLASTICOS'),
  ('actividad_economica', '1044010', 'TRADUCCION E INTERPRETACION LINGüISTICA - INTERPRETES Y/O TRADUCTORES'),
  ('actividad_economica', '1052010', 'PUBLICIDAD, PROPAGANDA Y RELACIONES PUBLICAS - MODELOS Y EDECANES'),
  ('actividad_economica', '1054010', 'PUBLICIDAD, PROPAGANDA Y RELACIONES PUBLICAS - DIRECTORES, GERENTES Y EMPLEADOS DE PUBLICIDAD'),
  ('actividad_economica', '1112010', 'INVESTIGACION - ENCUESTADORES Y CODIFICADORES'),
  ('actividad_economica', '1113010', 'INVESTIGACION - ASISTENTES DE INVESTIGADORES'),
  ('actividad_economica', '1113020', 'INVESTIGACION - QUIMICOS Y/O TECNICOS EN QUIMICA'),
  ('actividad_economica', '1114010', 'INVESTIGACION - BIOLOGOS Y CIENTIFICOS RELACIONADOS'),
  ('actividad_economica', '1114020', 'INVESTIGACION - ECONOMISTAS Y POLITOLOGOS (NO FUNCIONARIOS PUBLICOS)'),
  ('actividad_economica', '1114030', 'INVESTIGACION - FISICOS ASTRONOMOS'),
  ('actividad_economica', '1114040', 'INVESTIGACION - GEOLOGOS, GEOQUIMICOS, GEOFISICOS Y GEOGRAFOS'),
  ('actividad_economica', '1114050', 'INVESTIGACION - INVESTIGADORES Y CONSULTORES EN MERCADOTECNIA'),
  ('actividad_economica', '1114060', 'INVESTIGACION - MATEMATICOS, ESTADISTICOS Y ACTUARIOS'),
  ('actividad_economica', '1114070', 'INVESTIGACION - METEOROLOGOS'),
  ('actividad_economica', '1114090', 'INVESTIGACION - SOCIOLOGOS, ANTROPOLOGOS E HISTORIADORES'),
  ('actividad_economica', '1123020', 'ENSEÑANZA - CAPACITADORES E INSTRUCTORES'),
  ('actividad_economica', '1124070', 'ENSEÑANZA - PROFESORES O DOCENTES'),
  ('actividad_economica', '1125010', 'ENSEÑANZA - DIRECTORES GENERALES DE EDUCACION'),
  ('actividad_economica', '1133010', 'DIFUSION CULTURAL - PROMOTORES DE DIFUSION CULTURAL'),
  ('actividad_economica', '1134010', 'DIFUSION CULTURAL - TRABAJADORES DE BIBLIOTECA, ARCHIVO, MUSEO Y GALERIA DE ARTE'),
  ('actividad_economica', '1135010', 'OTRAS OCUPACIONES - ESTUDIANTE O MENOR DE EDAD SIN OCUPACION'),
  ('actividad_economica', '1135080', 'OTRAS OCUPACIONES - PROPIETARIO, ACCIONISTA O SOCIO'),
  ('actividad_economica', '1135020', 'OTRAS OCUPACIONES - DESEMPLEADO'),
  ('actividad_economica', '1135030', 'OTRAS OCUPACIONES - JUBILADO O PENSIONADO'),
  ('actividad_economica', '1135050', 'OTRAS OCUPACIONES - AMA DE CASA O QUEHACERES DEL HOGAR'),
  ('actividad_economica', '1135060', 'OTRAS OCUPACIONES - MINISTROS DE CULTO RELIGIOSO (SACERDOTE, PASTOR, MONJA, ETC)'),
  ('actividad_economica', '1135070', 'OTRAS OCUPACIONES - AGENTE ADUANAL'),
  ('actividad_economica', '1136010', 'SECTOR PUBLICO - EMPLEADO DEL PODER EJECUTIVO FEDERAL'),
  ('actividad_economica', '1136020', 'SECTOR PUBLICO - EMPLEADO PODER EJECUTIVO ESTATAL O DEL DISTRITO FEDERAL'),
  ('actividad_economica', '1136030', 'SECTOR PUBLICO - EMPLEADO DEL PODER EJECUTIVO MUNICIPAL O DELEGACIONAL'),
  ('actividad_economica', '1136040', 'SECTOR PUBLICO - EMPLEADO DEL PODER JUDICIAL FEDERAL'),
  ('actividad_economica', '1136070', 'SECTOR PUBLICO - EMPLEADO DEL PODER JUDICIAL ESTATAL O DEL DISTRITO FEDERAL'),
  ('actividad_economica', '1136050', 'SECTOR PUBLICO - EMPLEADO DEL PODER LEGISLATIVO FEDERAL'),
  ('actividad_economica', '1136060', 'SECTOR PUBLICO - EMPLEADO DEL PODER LEGISLATIVO ESTATAL O DEL DISTRITO FEDERAL'),
  ('actividad_economica', '1136090', 'SECTOR PUBLICO - EJERCITO, ARMADA Y FUERZA AEREA'),
  ('actividad_economica', '1136080', 'ORGANISMOS INTERNACIONALES Y EXTRATERRITORIALES - EMPLEADOS DE ORGANISMOS INTERNACIONALES Y EXTRATERRITORIALES'),
  ('giro_mercantil', '1000000', 'NO APLICA'),
  ('giro_mercantil', '1100001', 'SECTOR PRIMARIO - AGRICULTURA'),
  ('giro_mercantil', '1200001', 'SECTOR PRIMARIO - GANADERIA'),
  ('giro_mercantil', '1300001', 'SECTOR PRIMARIO - EXPLOTACION DE OTROS ANIMALES (AVICULTURA, APICULTURA, ETC.)'),
  ('giro_mercantil', '1400002', 'SECTOR PRIMARIO - APROVECHAMIENTO FORESTAL'),
  ('giro_mercantil', '1500001', 'SECTOR PRIMARIO - PESCA'),
  ('giro_mercantil', '2100002', 'MINERIA - MINERIA DE OTROS RECURSOS'),
  ('giro_mercantil', '2200002', 'MINERIA - ACTIVIDADES RELACIONADAS CON EL PETROLEO Y EL GAS'),
  ('giro_mercantil', '2300003', 'MINERIA - ORO'),
  ('giro_mercantil', '2400002', 'MINERIA - PLATA'),
  ('giro_mercantil', '2500002', 'MINERIA - PIEDRAS PRECIOSAS'),
  ('giro_mercantil', '2600003', 'GENERACION, TRANSMISION Y DISTRIBUCION DE ENERGIA ELECTRICA, SUMINISTRO DE AGUA Y DE GAS'),
  ('giro_mercantil', '2710004', 'CONSTRUCCION - OTRAS ACTIVIDADES RELACIONADAS CON LA CONSTRUCCION'),
  ('giro_mercantil', '2720004', 'CONSTRUCCION - EDIFICACION RESIDENCIAL Y NO RESIDENCIAL'),
  ('giro_mercantil', '2730004', 'CONSTRUCCION - OBRAS DE INGENIERIA CIVIL'),
  ('giro_mercantil', '2740004', 'CONSTRUCCION - TRABAJOS ESPECIALIZADOS PARA LA CONSTRUCCION'),
  ('giro_mercantil', '2754004', 'CONSTRUCCION - SERVICIOS DE BLINDAJE PARCIAL O TOTAL DE INMUEBLES'),
  ('giro_mercantil', '3110005', 'INDUSTRIA - ALIMENTARIA'),
  ('giro_mercantil', '3120005', 'INDUSTRIA - BEBIDAS Y DEL TABACO'),
  ('giro_mercantil', '3140005', 'INDUSTRIA - PRODUCTOS TEXTILES'),
  ('giro_mercantil', '3150005', 'INDUSTRIA - PRENDAS DE VESTIR'),
  ('giro_mercantil', '3210005', 'INDUSTRIA - MADERA'),
  ('giro_mercantil', '3220005', 'INDUSTRIA - PAPEL'),
  ('giro_mercantil', '3230005', 'INDUSTRIA - IMPRESION E INDUSTRIAS CONEXAS'),
  ('giro_mercantil', '3240005', 'INDUSTRIA - PRODUCTOS DERIVADOS DEL PETROLEO Y DEL CARBON'),
  ('giro_mercantil', '3250005', 'INDUSTRIA - QUIMICA'),
  ('giro_mercantil', '3260005', 'INDUSTRIA - PLASTICO Y DEL HULE'),
  ('giro_mercantil', '3270005', 'INDUSTRIA - PRODUCTOS A BASE DE MINERALES NO METALICOS (ALFARERIA, PORCELANA, LOZA, VIDRIO, CEMENTO)'),
  ('giro_mercantil', '3310005', 'INDUSTRIA - METALICAS BASICAS'),
  ('giro_mercantil', '3320005', 'INDUSTRIA - PRODUCTOS METALICOS (HERRAMIENTAS, UTENSILIOS, ESTRUCTURAS, PIEZAS)'),
  ('giro_mercantil', '3330005', 'INDUSTRIA - MAQUINARIA Y EQUIPO'),
  ('giro_mercantil', '3340005', 'INDUSTRIA - EQUIPO DE COMPUTACION, COMUNICACION, MEDICION Y DE OTROS EQUIPOS, COMPONENTES Y ACCESORIOS ELECTRONICOS'),
  ('giro_mercantil', '3350005', 'INDUSTRIA - ACCESORIOS, APARATOS ELECTRICOS Y EQUIPO DE GENERACION DE ENERGIA ELECTRICA'),
  ('giro_mercantil', '3360005', 'INDUSTRIA - EQUIPO DE TRANSPORTE SIN MOTOR'),
  ('giro_mercantil', '3370005', 'INDUSTRIA - AUTOMOTRIZ'),
  ('giro_mercantil', '3380005', 'INDUSTRIA - VEHICULOS BLINDADOS Y EQUIPO PARA EL BLINDAJE DE VEHICULOS'),
  ('giro_mercantil', '3410005', 'INDUSTRIA - MUEBLES, COLCHONES Y PERSIANAS'),
  ('giro_mercantil', '3420005', 'INDUSTRIA - OTRAS INDUSTRIAS MANUFACTURERAS'),
  ('giro_mercantil', '3430005', 'INDUSTRIA - ORFEBRERIA Y JOYERIA DE METALES Y PIEDRAS PRECIOSOS'),
  ('giro_mercantil', '3440005', 'INDUSTRIA - JOYERIA DE METALES Y PIEDRAS NO PRECIOSOS Y DE OTROS MATERIALES'),
  ('giro_mercantil', '4310006', 'COMERCIO - ABARROTES, ALIMENTOS, BEBIDAS, HIELO Y TABACO'),
  ('giro_mercantil', '4320006', 'COMERCIO - PRODUCTOS FARMACEUTICOS, DE PERFUMERIA, ARTICULOS PARA EL ESPARCIMIENTO, ELECTRODOMESTICOS Y APARATOS DE LINEA BLANCA'),
  ('giro_mercantil', '4330006', 'COMERCIO - MATERIAS PRIMAS AGROPECUARIAS Y FORESTALES, PARA LA INDUSTRIA, Y MATERIALES DE DESECHO'),
  ('giro_mercantil', '4340006', 'COMERCIO - MAQUINARIA, EQUIPO DE COMPUTO Y MOBILIARIO DE USO GENERAL'),
  ('giro_mercantil', '4620006', 'COMERCIO - TIENDAS DE AUTOSERVICIO Y DEPARTAMENTALES'),
  ('giro_mercantil', '4630006', 'COMERCIO - PRODUCTOS TEXTILES, BISUTERIA, ACCESORIOS DE VESTIR Y CALZADO'),
  ('giro_mercantil', '4650006', 'COMERCIO - ARTICULOS DE PAPELERIA'),
  ('giro_mercantil', '4660026', 'COMERCIO - ARTICULOS DE JOYERIA Y RELOJES'),
  ('giro_mercantil', '4670006', 'COMERCIO - ARTICULOS PARA LA DECORACION DE INTERIORES'),
  ('giro_mercantil', '4680006', 'COMERCIO - ANTIGÜEDADES Y OBRAS DE ARTE'),
  ('giro_mercantil', '4710006', 'COMERCIO - ARTICULOS DE FERRETERIA, TLAPALERIA Y VIDRIOS'),
  ('giro_mercantil', '4720006', 'COMERCIO - VEHICULOS NUEVOS'),
  ('giro_mercantil', '4730006', 'COMERCIO - VEHICULOS USADOS'),
  ('giro_mercantil', '4740006', 'COMERCIO - PARTES Y REFACCIONES PARA VEHICULOS'),
  ('giro_mercantil', '4750006', 'COMERCIO - COMBUSTIBLES Y LUBRICANTES'),
  ('giro_mercantil', '4760006', 'COMERCIO - A TRAVES DE INTERNET, Y CATALOGOS IMPRESOS, TELEVISION Y SIMILARES'),
  ('giro_mercantil', '4810007', 'TRANSPORTE - AEREO'),
  ('giro_mercantil', '4820007', 'TRANSPORTE - FERROVIARIO'),
  ('giro_mercantil', '4830007', 'TRANSPORTE - MARITIMO Y FLUVIAL'),
  ('giro_mercantil', '4850007', 'TRANSPORTE - TERRESTRE'),
  ('giro_mercantil', '4860007', 'TRANSPORTE - TRANSPORTACION Y DISTRIBUCION POR DUCTOS'),
  ('giro_mercantil', '4880007', 'TRANSPORTE - SERVICIOS RELACIONADOS CON EL TRANSPORTE'),
  ('giro_mercantil', '4890007', 'TRANSPORTE - SERVICIOS DE AGENCIAS ADUANALES'),
  ('giro_mercantil', '4840007', 'TRANSPORTE - SERVICIOS DE TRANSPORTE Y/O CUSTODIA DE VALORES'),
  ('giro_mercantil', '4910008', 'SERVICIOS POSTALES'),
  ('giro_mercantil', '4920009', 'SERVICIOS DE MENSAJERIA Y PAQUETERIA'),
  ('giro_mercantil', '4930010', 'SERVICIOS DE ALMACENAMIENTO'),
  ('giro_mercantil', '5100011', 'INFORMACION EN MEDIOS MASIVOS'),
  ('giro_mercantil', '5180012', 'PROCESAMIENTO ELECTRONICO DE INFORMACION Y OTROS SERVICIOS WEB'),
  ('giro_mercantil', '5210013', 'SERVICIOS FINANCIEROS - BANCA CENTRAL'),
  ('giro_mercantil', '5220013', 'SERVICIOS FINANCIEROS - BANCA MULTIPLE'),
  ('giro_mercantil', '5230013', 'SERVICIOS FINANCIEROS - BANCA DE DESARROLLO'),
  ('giro_mercantil', '5240013', 'SERVICIOS FINANCIEROS - FONDOS Y FIDEICOMISOS FINANCIEROS'),
  ('giro_mercantil', '5250013', 'SERVICIOS FINANCIEROS - UNIONES DE CREDITO'),
  ('giro_mercantil', '5260013', 'SREVICIOS FINANCIEROS - CAJAS DE AHORRO POPULAR'),
  ('giro_mercantil', '5270013', 'SERVICIOS FINANCIEROS - OTRAS INSTITUCIONES DE INTERMEDIACION CREDITICIA Y FINANCIERA NO BURSATIL (OPERACION Y PROMOCION DE TARJETAS DE CREDITO NO BANCARIAS,  FINANCIAMIENTO DE BIENES DURADEROS), SOCIEDADES FINANCIERAS DE OBJETO LIMITADO'),
  ('giro_mercantil', '5280013', 'SERVICIOS FINANCIEROS - OTRAS INSTITUCIONES DE AHORRO Y PRESTAMO'),
  ('giro_mercantil', '5290013', 'SERVICIOS FINANCIEROS - COMPAÑIAS DE AUTOFINANCIAMIENTO'),
  ('giro_mercantil', '5310013', 'SERVICIOS FINANCIEROS - MONTEPIOS'),
  ('giro_mercantil', '5320013', 'SERVICIOS FINANCIEROS - CASAS DE EMPEÑO'),
  ('giro_mercantil', '5330013', 'SERVICIOS FINANCIEROS - SOCIEDADES FINANCIERAS DE OBJETO MULTIPLE'),
  ('giro_mercantil', '5350013', 'SERVICIOS FINANCIEROS - CASAS DE BOLSA'),
  ('giro_mercantil', '5360013', 'SERVICIOS FINANCIEROS - CASAS DE CAMBIO Y CENTROS CAMBIARIOS'),
  ('giro_mercantil', '5370013', 'SERVICIOS FINANCIEROS - TRANSMISORES DE DINERO'),
  ('giro_mercantil', '5390013', 'SERVICIOS FINANCIEROS - OTROS SERVICIOS RELACIONADOS CON LA INTERMEDIACION BURSATIL'),
  ('giro_mercantil', '5410013', 'SERVICIOS FINANCIEROS - COMPAÑIAS DE SEGUROS'),
  ('giro_mercantil', '5420013', 'SERVICIOS FINANCIEROS - COMPAÑIAS AFIANZADORAS'),
  ('giro_mercantil', '5430013', 'SERVICIOS FINANCIEROS - AGENTES, AJUSTADORES Y GESTORES DE SEGUROS Y FIANZAS'),
  ('giro_mercantil', '5440013', 'SERVICIOS FINANCIEROS - ADMINISTRACION DE FONDOS PARA EL RETIRO'),
  ('giro_mercantil', '5450013', 'SERVICIOS FINANCIEROS - EMISORA Y/O COMERCIALIZACION DE CHEQUES DE VIAJERO'),
  ('giro_mercantil', '5340013', 'OTRAS EMPRESAS DE INTERMEDIACION CREDITICIA NO FINANCIERAS'),
  ('giro_mercantil', '5510014', 'SERVICIOS INMOBILIARIOS Y DE ALQUILER - ALQUILER SIN INTERMEDIACION DE BIENES RAICES'),
  ('giro_mercantil', '5520014', 'SERVICIOS INMOBILIARIOS Y DE ALQUILER - INMOBILIARIAS Y CORREDORES DE BIENES RAICES'),
  ('giro_mercantil', '5530014', 'SERVICIOS INMOBILIARIOS Y DE ALQUILER - SERVICIOS DE ALQUILER DE BIENES MUEBLES EXCEPTO VEHICULOS'),
  ('giro_mercantil', '5540014', 'SERVICIOS INMOBILIARIOS Y DE ALQUILER - ALQUILER DE VEHICULOS'),
  ('giro_mercantil', '5550014', 'SERVICIOS INMOBILIARIOS Y DE ALQUILER - SERVICIOS DE ALQUILER DE MARCAS REGISTRADAS, PATENTES Y FRANQUICIAS'),
  ('giro_mercantil', '5610015', 'SERVICIOS PROFESIONALES Y TECNICOS - SERVICIOS JURIDICOS'),
  ('giro_mercantil', '5620015', 'SERVICIOS PROFESIONALES Y TECNICOS - NOTARIA Y CORREDURIA PUBLICA'),
  ('giro_mercantil', '5690015', 'SERVICIOS PROFESIONALES Y TECNICOS - CONTABILIDAD Y AUDITORIA'),
  ('giro_mercantil', '5630015', 'SERVICIOS PROFESIONALES Y TECNICOS - ARQUITECTURA, INGENIERIA Y ACTIVIDADES RELACIONADAS'),
  ('giro_mercantil', '5640015', 'SERVICIOS PROFESIONALES Y TECNICOS - DISEÑO DE SISTEMAS DE COMPUTO Y SERVICIOS RELACIONADOS'),
  ('giro_mercantil', '5650015', 'SERVICIOS PROFESIONALES Y TECNICOS - CONSULTORIA ADMINISTRATIVA, CIENTIFICA Y TECNICA'),
  ('giro_mercantil', '5660015', 'SERVICIOS PROFESIONALES Y TECNICOS - INVESTIGACION CIENTIFICA Y DESARROLLO'),
  ('giro_mercantil', '5670015', 'SERVICIOS PROFESIONALES Y TECNICOS - PUBLICIDAD Y ACTIVIDADES RELACIONADAS'),
  ('giro_mercantil', '5680015', 'SERVICIOS PROFESIONALES Y TECNICOS - OTROS SERVICIOS DE OUTSOURCING'),
  ('giro_mercantil', '5710016', 'SERVICIOS DE APOYO A LOS NEGOCIOS - SERVICIOS DE ADMINISTRACION DE NEGOCIOS'),
  ('giro_mercantil', '5720016', 'SERVICIOS DE APOYO A LOS NEGOCIOS - AGENCIAS DE COBRANZA, DESPACHOS DE INVESTIGACION'),
  ('giro_mercantil', '5730016', 'SERVICIOS DE APOYO A LOS NEGOCIOS - SERVICIOS DE PROTECCION Y SEGURIDAD'),
  ('giro_mercantil', '5740016', 'SERVICIOS DE APOYO A LOS NEGOCIOS - SERVICIOS DE LIMPIEZA Y MANTENIMIENTO'),
  ('giro_mercantil', '5750016', 'SERVICIOS DE APOYO A LOS NEGOCIOS - OTROS SERVICIOS'),
  ('giro_mercantil', '6100017', 'SERVICIOS EDUCATIVOS'),
  ('giro_mercantil', '6200018', 'SERVICIOS DE SALUD Y DE ASISTENCIA SOCIAL'),
  ('giro_mercantil', '7110019', 'SERVICIOS DE ESPARCIMIENTO CULTURALES Y DEPORTIVOS, Y OTROS SERVICIOS RECREATIVOS'),
  ('giro_mercantil', '7120019', 'SERVICIOS DE ESPARCIMIENTO - MUSEOS, SITIOS HISTORICOS, ZOOLOGICOS Y SIMILARES'),
  ('giro_mercantil', '7130019', 'SERVICIOS DE ESPARCIMIENTO - CASAS DE JUEGOS ELECTRONICOS'),
  ('giro_mercantil', '7140019', 'SERVICIOS DE ESPARCIMIENTO - CASINOS O CENTROS DE APUESTA'),
  ('giro_mercantil', '7150019', 'SERVICIOS DE ESPARCIMIENTO - VENTA DE BILLETES DE LOTERIA, PRONOSTICOS DEPORTIVOS U OTROS SORTEOS'),
  ('giro_mercantil', '7200020', 'SERVICIOS DE ALOJAMIENTO TEMPORAL Y DE PREPARACION DE ALIMENTOS Y BEBIDAS'),
  ('giro_mercantil', '8100021', 'SERVICIOS DE REPARACION Y MANTENIMIENTO - EQUIPO INDUSTRIAL, COMERCIAL, SERVICIOS Y AUTOMOTRIZ'),
  ('giro_mercantil', '8200022', 'SERVICIOS PERSONALES - LAVANDERIAS, SERVICIOS FUNERARIOS, BAÑOS PUBLICOS, SERVICIOS DE ESTACIONAMIENTO, REVELADO E IMPRESION DE FOTOGRAFIAS'),
  ('giro_mercantil', '8310023', 'ASOCIACIONES - ORGANIZACIONES Y CAMARAS DE PRODUCTORES, COMERCIANTES Y PRESTADORES DE SERVICIOS'),
  ('giro_mercantil', '8320023', 'ASOCIACIONES - ORGANIZACIONES LABORALES Y SINDICALES'),
  ('giro_mercantil', '8330023', 'ASOCIACIONES - ORGANIZACIONES DE PROFESIONISTAS'),
  ('giro_mercantil', '8340023', 'ASOCIACIONES - ORGANIZACIONES DE ACTIVIDADES RECREATIVAS'),
  ('giro_mercantil', '8350023', 'ASOCIACIONES - ORGANIZACIONES RELIGIOSAS'),
  ('giro_mercantil', '8360023', 'ASOCIACIONES - ORGANIZACIONES POLITICAS'),
  ('giro_mercantil', '8370023', 'ASOCIACIONES - ORGANIZACIONES CIVILES'),
  ('giro_mercantil', '9100025', 'ORGANISMOS INTERNACIONALES Y EXTRATERRITORIALES'),
  ('giro_mercantil', '9810024', 'SECTOR PUBLICO - PODER EJECUTIVO FEDERAL'),
  ('giro_mercantil', '9820024', 'SECTOR PUBLICO - PODER EJECUTIVO ESTATAL Y DEL DISTRITO FEDERAL'),
  ('giro_mercantil', '9830024', 'SECTOR PUBLICO - PODER EJECUTIVO MUNICIPAL Y DELEGACIONAL'),
  ('giro_mercantil', '9840024', 'SECTOR PUBLICO - PODER JUDICIAL FEDERAL'),
  ('giro_mercantil', '9850024', 'SECTOR PUBLICO - PODER JUDICIAL ESTATAL Y DEL DISTRITO FEDERAL'),
  ('giro_mercantil', '9860024', 'SECTOR PUBLICO - PODER LEGISLATIVO FEDERAL'),
  ('giro_mercantil', '9870024', 'SECTOR PUBLICO - PODER LEGISLATIVO ESTATAL Y DEL DISTRITO FEDERAL'),
  ('giro_mercantil', '9880024', 'SECTOR PUBLICO - ORGANOS AUTONOMOS Y ENTIDADES PARAESTATALES'),
  ('tipo_desarrollo', '1', 'Habitacional'),
  ('tipo_desarrollo', '2', 'Comercial'),
  ('tipo_desarrollo', '3', 'Oficinas'),
  ('tipo_desarrollo', '4', 'Industrial'),
  ('tipo_desarrollo', '5', 'Mixto (Habitacional y Comercial)'),
  ('tipo_desarrollo', '99', 'Otro'),
  ('tipo_tercero', '1', 'Proveedores'),
  ('tipo_tercero', '2', 'Cliente(s) en Preventa'),
  ('tipo_tercero', '99', 'Otro'),
  ('instrumento_monetario', '1', 'Efectivo'),
  ('instrumento_monetario', '2', 'Tarjeta de Crédito'),
  ('instrumento_monetario', '3', 'Tarjeta de Debito'),
  ('instrumento_monetario', '4', 'Tarjeta de Prepago'),
  ('instrumento_monetario', '5', 'Cheque Nominativo'),
  ('instrumento_monetario', '6', 'Cheque de Caja'),
  ('instrumento_monetario', '7', 'Cheques de Viajero'),
  ('instrumento_monetario', '8', 'Transferencia Interbancaria'),
  ('instrumento_monetario', '9', 'Transferencia Misma Institución'),
  ('instrumento_monetario', '10', 'Transferencia Internacional'),
  ('instrumento_monetario', '11', 'Orden de Pago'),
  ('instrumento_monetario', '12', 'Giro'),
  ('instrumento_monetario', '13', 'Oro o Platino Amonedados'),
  ('instrumento_monetario', '14', 'Plata Amonedada'),
  ('instrumento_monetario', '15', 'Metales Preciosos'),
  ('tipo_institucion', '4', 'Administradoras de Fondos para el Retiro'),
  ('tipo_institucion', '7', 'Almacenes Generales de Deposito'),
  ('tipo_institucion', '10', 'Arrendadoras Financieras'),
  ('tipo_institucion', '13', 'Casas de Bolsa'),
  ('tipo_institucion', '16', 'Casas de Cambio'),
  ('tipo_institucion', '18', 'Sector Energía'),
  ('tipo_institucion', '19', 'Empresas de Factoraje Financiero'),
  ('tipo_institucion', '22', 'Instituciones de Seguros'),
  ('tipo_institucion', '25', 'Empresas de Servicios a Intermediarios Bursátiles'),
  ('tipo_institucion', '27', 'Sociedades Financieras Populares'),
  ('tipo_institucion', '28', 'Servicios Complementarios'),
  ('tipo_institucion', '29', 'Entidades de Ahorro y Crédito Popular'),
  ('tipo_institucion', '30', 'Organismos de Integración'),
  ('tipo_institucion', '31', 'Fondos y Fideicomisos de Fomento Económico'),
  ('tipo_institucion', '32', 'Organismos de Servicio Social'),
  ('tipo_institucion', '34', 'Inmobiliarias'),
  ('tipo_institucion', '37', 'Banca de Desarrollo'),
  ('tipo_institucion', '40', 'Banca Múltiple'),
  ('tipo_institucion', '43', 'Instituciones de Fianzas'),
  ('tipo_institucion', '46', 'Oficinas de Representación de Intermediarios Financieros del Exterior'),
  ('tipo_institucion', '50', 'Financiera Rural'),
  ('tipo_institucion', '52', 'Sociedades de Inversión'),
  ('tipo_institucion', '55', 'Sociedades Controladoras'),
  ('tipo_institucion', '61', 'Sociedades de Información Crediticia'),
  ('tipo_institucion', '64', 'Sociedades de Inversión Especializadas de Fondos para el Retiro'),
  ('tipo_institucion', '67', 'Sociedades Financieras de Objeto Limitado'),
  ('tipo_institucion', '68', 'Sociedades Financieras de Objeto Múltiple'),
  ('tipo_institucion', '69', 'Sociedades Financieras de Objeto Múltiple (Entidades No Reguladas)'),
  ('tipo_institucion', '70', 'Sociedades Operadoras de Sociedades de Inversión'),
  ('tipo_institucion', '71', 'Sociedades Distribuidoras de Acciones de Sociedades de Inversión'),
  ('tipo_institucion', '72', 'Valuadoras de Acciones de Sociedades de Inversión'),
  ('tipo_institucion', '79', 'Sucursales en el Extranjero'),
  ('tipo_institucion', '85', 'Uniones de Crédito'),
  ('tipo_institucion', '88', 'Transmisores de Dinero'),
  ('tipo_institucion', '89', 'Centros Cambiarios'),
  ('tipo_institucion', '90', 'Asesores en Inversiones'),
  ('tipo_institucion', '99', 'Otros Organismos No Financieros'),
  ('moneda', '1', 'Peso mexicano'),
  ('moneda', '2', 'Dólar estadounidense'),
  ('moneda', '3', 'Euro'),
  ('moneda', '4', 'Dirham de los Emiratos Árabes Unidos'),
  ('moneda', '5', 'Afgani afgano'),
  ('moneda', '6', 'Lek albanés'),
  ('moneda', '7', 'Dram armenio'),
  ('moneda', '8', 'Florín antillano neerlandés'),
  ('moneda', '9', 'Kwanza angoleño'),
  ('moneda', '10', 'Peso argentino'),
  ('moneda', '11', 'Dólar australiano'),
  ('moneda', '12', 'Florín arubeño'),
  ('moneda', '13', 'Manat azerbaiyano'),
  ('moneda', '14', 'Manat azerbaiyano'),
  ('moneda', '15', 'Marco convertible de Bosnia-Herzegovina'),
  ('moneda', '16', 'Dólar de Barbados'),
  ('moneda', '17', 'Taka de Bangladesh'),
  ('moneda', '18', 'Lev búlgaro'),
  ('moneda', '19', 'Dinar bahreiní'),
  ('moneda', '20', 'Franco burundés'),
  ('moneda', '21', 'Dólar de Bermuda'),
  ('moneda', '22', 'Dólar de Brunéi'),
  ('moneda', '23', 'Boliviano'),
  ('moneda', '24', 'Real brasileño'),
  ('moneda', '25', 'Dólar bahameño'),
  ('moneda', '26', 'Ngultrum de Bután'),
  ('moneda', '27', 'Pula de Botsuana'),
  ('moneda', '28', 'Rublo bielorruso'),
  ('moneda', '29', 'Dólar de Belice'),
  ('moneda', '30', 'Dólar canadiense'),
  ('moneda', '31', 'Franco congoleño, o congolés'),
  ('moneda', '32', 'Franco suizo'),
  ('moneda', '33', 'Peso chileno'),
  ('moneda', '34', 'Yuan chino'),
  ('moneda', '35', 'Peso colombiano'),
  ('moneda', '36', 'Colón costarricense'),
  ('moneda', '37', 'Dinar serbio'),
  ('moneda', '38', 'Peso cubano convertible'),
  ('moneda', '39', 'Peso cubano'),
  ('moneda', '40', 'Escudo caboverdiano'),
  ('moneda', '41', 'Koruna checa'),
  ('moneda', '42', 'Franco yibutiano'),
  ('moneda', '43', 'Corona danesa'),
  ('moneda', '44', 'Peso dominicano'),
  ('moneda', '45', 'Dinar algerino'),
  ('moneda', '46', 'Libra egipcia'),
  ('moneda', '47', 'Nakfa eritreo'),
  ('moneda', '48', 'Birr etíope'),
  ('moneda', '49', 'Dólar fiyiano'),
  ('moneda', '50', 'Libra malvinense'),
  ('moneda', '51', 'Libra esterlina (libra de Gran Bretaña)'),
  ('moneda', '52', 'Lari georgiano'),
  ('moneda', '53', 'Cedi ghanés'),
  ('moneda', '54', 'Libra de Gibraltar'),
  ('moneda', '55', 'Dalasi gambiano'),
  ('moneda', '56', 'Franco guineano'),
  ('moneda', '57', 'Quetzal guatemalteco'),
  ('moneda', '58', 'Dólar guyanés'),
  ('moneda', '59', 'Dólar de Hong Kong'),
  ('moneda', '60', 'Lempira hondureño'),
  ('moneda', '61', 'Kuna croata'),
  ('moneda', '62', 'Gourde haitiano'),
  ('moneda', '63', 'Forint húngaro'),
  ('moneda', '64', 'Rupiah indonesia'),
  ('moneda', '65', 'Nuevo shéquel israelí'),
  ('moneda', '66', 'Rupia india'),
  ('moneda', '67', 'Dinar iraquí'),
  ('moneda', '68', 'Rial iraní'),
  ('moneda', '69', 'Króna islandesa'),
  ('moneda', '70', 'Dólar jamaicano'),
  ('moneda', '71', 'Dinar jordano'),
  ('moneda', '72', 'Yen japonés'),
  ('moneda', '73', 'Chelín keniata'),
  ('moneda', '74', 'Som kirguís (de Kirguistán)'),
  ('moneda', '75', 'Riel camboyano'),
  ('moneda', '76', 'Franco comoriano (de Comoras)'),
  ('moneda', '77', 'Won norcoreano'),
  ('moneda', '78', 'Won surcoreano'),
  ('moneda', '79', 'Dinar kuwaití'),
  ('moneda', '80', 'Dólar caimano (de Islas Caimán)'),
  ('moneda', '81', 'Tenge kazajo'),
  ('moneda', '82', 'Kip lao'),
  ('moneda', '83', 'Libra libanesa'),
  ('moneda', '84', 'Rupia de Sri Lanka'),
  ('moneda', '85', 'Dólar liberiano'),
  ('moneda', '86', 'Loti lesotense'),
  ('moneda', '87', 'Litas lituano'),
  ('moneda', '88', 'Lat letón'),
  ('moneda', '89', 'Dinar libio'),
  ('moneda', '90', 'Dirham marroquí'),
  ('moneda', '91', 'Leu moldavo'),
  ('moneda', '92', 'Ariary malgache'),
  ('moneda', '93', 'Denar macedonio'),
  ('moneda', '94', 'Kyat birmano'),
  ('moneda', '95', 'Tughrik mongol'),
  ('moneda', '96', 'Pataca de Macao'),
  ('moneda', '97', 'Ouguiya mauritana'),
  ('moneda', '98', 'Rupia mauricia'),
  ('moneda', '99', 'Rufiyaa maldiva'),
  ('moneda', '100', 'Kwacha malauí'),
  ('moneda', '101', 'Ringgit malayo'),
  ('moneda', '102', 'Metical mozambiqueño'),
  ('moneda', '103', 'Dólar namibio'),
  ('moneda', '104', 'Naira nigeriana'),
  ('moneda', '105', 'Córdoba nicaragüense'),
  ('moneda', '106', 'Corona noruega'),
  ('moneda', '107', 'Rupia nepalesa'),
  ('moneda', '108', 'Dólar neozelandés'),
  ('moneda', '109', 'Rial omaní'),
  ('moneda', '110', 'Balboa panameña'),
  ('moneda', '111', 'Nuevo sol peruano'),
  ('moneda', '112', 'Kina de Papúa Nueva Guinea'),
  ('moneda', '113', 'Peso filipino'),
  ('moneda', '114', 'Rupia pakistaní'),
  ('moneda', '115', 'zloty polaco'),
  ('moneda', '116', 'Guaraní paraguayo'),
  ('moneda', '117', 'Rial qatarí'),
  ('moneda', '118', 'Leu rumano'),
  ('moneda', '119', 'Dinar serbio'),
  ('moneda', '120', 'Rublo ruso'),
  ('moneda', '121', 'Franco ruandés'),
  ('moneda', '122', 'Riyal saudí'),
  ('moneda', '123', 'Dólar de las Islas Salomón'),
  ('moneda', '124', 'Rupia de Seychelles'),
  ('moneda', '125', 'Dinar sudanés'),
  ('moneda', '126', 'Corona sueca'),
  ('moneda', '127', 'Dólar de Singapur'),
  ('moneda', '128', 'Libra de Santa Helena'),
  ('moneda', '129', 'Leone de Sierra Leona'),
  ('moneda', '130', 'Chelín somalí'),
  ('moneda', '131', 'Dólar surinamés'),
  ('moneda', '132', 'Libra de Sudán del Sur'),
  ('moneda', '133', 'Dobra de Santo Tomé y Príncipe'),
  ('moneda', '134', 'Colón Salvadoreño'),
  ('moneda', '135', 'Libra siria'),
  ('moneda', '136', 'Lilangeni suazi'),
  ('moneda', '137', 'Baht tailandés'),
  ('moneda', '138', 'Somoni tayik (de Tayikistán)'),
  ('moneda', '139', 'Manat turcomano'),
  ('moneda', '140', 'Dinar tunecino'),
  ('moneda', '141', 'Pa''anga tongano'),
  ('moneda', '142', 'Lira turca'),
  ('moneda', '143', 'Dólar de Trinidad y Tobago'),
  ('moneda', '144', 'Dólar taiwanés'),
  ('moneda', '145', 'Chelín tanzano'),
  ('moneda', '146', 'Grivna ucraniana'),
  ('moneda', '147', 'Chelín ugandés'),
  ('moneda', '148', 'Peso uruguayo'),
  ('moneda', '149', 'Som uzbeko'),
  ('moneda', '150', 'Bolívar fuerte venezolano'),
  ('moneda', '151', 'Dong vietnamita'),
  ('moneda', '152', 'Vatu vanuatense'),
  ('moneda', '153', 'Tala samoana'),
  ('moneda', '154', 'Rial yemení (de Yemen)'),
  ('moneda', '155', 'Rand sudafricano'),
  ('moneda', '156', 'Kwacha zambiano'),
  ('moneda', '157', 'Kwacha zambiano'),
  ('moneda', '158', 'Dólar zimbabuense'),
  ('moneda', '159', 'CENTENARIO'),
  ('moneda', '160', 'AZTECA'),
  ('moneda', '161', 'HIDALGO'),
  ('moneda', '162', '1/2 HIDALGO'),
  ('moneda', '163', '1/4 HIDALGO'),
  ('moneda', '164', '1/5 HIDALGO'),
  ('moneda', '165', '1 OZ LIBERTAD DE ORO'),
  ('moneda', '166', '1/2 OZ LIBERTAD DE ORO'),
  ('moneda', '167', '1/4 OZ LIBERTAD DE ORO'),
  ('moneda', '168', '1/10 OZ LIBERTAD DE ORO'),
  ('moneda', '169', '1/20 OZ LIBERTAD DE ORO'),
  ('moneda', '170', '1 OZ LIBERTAD DE PLATA'),
  ('moneda', '171', '1/2 OZ LIBERTAD DE PLATA'),
  ('moneda', '172', '1/4 OZ LIBERTAD DE PLATA'),
  ('moneda', '173', '1/10 OZ LIBERTAD DE PLATA'),
  ('moneda', '174', '1/20 OZ LIBERTAD DE PLATA'),
  ('moneda', '175', 'Onza de plata'),
  ('moneda', '176', 'Onza de oro'),
  ('moneda', '177', 'Franco de oro (Special settlement currency)'),
  ('moneda', '178', 'Onza de paladio'),
  ('moneda', '179', 'Onza de platino'),
  ('moneda', '180', 'Franco CFA de África Central'),
  ('moneda', '181', 'Dólar del Caribe Oriental'),
  ('moneda', '182', 'Franco UIC (Special settlement currency)'),
  ('moneda', '183', 'Franco CFA de África Occidental'),
  ('moneda', '184', 'Franco CFP'),
  ('tipo_credito', '1', 'Crédito Corporativo'),
  ('tipo_credito', '2', 'Crédito Puente'),
  ('tipo_credito', '3', 'Crédito Hipotecario'),
  ('prioridad', '1', 'NORMAL'),
  ('prioridad', '2', '24 HORAS CON OPERACIONES')
) as v(catalogo, codigo, descripcion);

-- ---------------------------------------------------------------------------
-- catalogos_sat es global: se declara exenta de tenant_id
-- ---------------------------------------------------------------------------
-- La aserción app.verificar_tenancy() detectó esta tabla al crearla, que es
-- justo su trabajo: ninguna tabla nueva se queda sin tenant_id por descuido.
-- Es catálogo regulatorio, igual que umbrales o uma_vigencias, así que la
-- excepción se declara aquí, en la misma migración que la crea.
create or replace function app.verificar_tenancy()
returns table (tabla text, problema text)
language sql
stable
set search_path = ''
as $$
  with exentas(nombre) as (
    values ('uma_vigencias'), ('actividades_vulnerables'), ('umbrales'),
           ('campos_expediente'), ('formatos_aviso'), ('parametros_motor'),
           ('catalogos_sat'),
           ('tenants'), ('usuarios'), ('personas')
  )
  select c.relname::text, 'no tiene columna tenant_id y no está en la lista de exentas'
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public'
    and c.relkind = 'r'
    and c.relname not in (select nombre from exentas)
    and not exists (
      select 1 from pg_attribute a
      where a.attrelid = c.oid and a.attname = 'tenant_id'
        and a.attnum > 0 and not a.attisdropped
    );
$$;

-- ---------------------------------------------------------------------------
-- Verificación: los valores que el MVP necesita sí están
-- ---------------------------------------------------------------------------
do $$
begin
  raise notice 'Catálogos del SAT: % valores en % catálogos',
    (select count(*) from catalogos_sat),
    (select count(distinct catalogo) from catalogos_sat);

  -- El comprador en preventa entra al aviso como tercero tipo 2. Si este
  -- código no existe, el mapeo del caso de uso central está roto.
  if not app.codigo_valido('tipo_tercero', '2', '2026-02-15') then
    raise exception 'Falta el código de tercero "Cliente(s) en Preventa"';
  end if;

  -- Único tipo de operación de la fracción.
  if not app.codigo_valido('tipo_operacion', '1601', '2026-02-15') then
    raise exception 'Falta el tipo de operación 1601 (Aportación a Desarrollos Inmobiliarios)';
  end if;

  -- El aviso de 24 horas YA existe en el formato vigente como prioridad 2.
  if not app.codigo_valido('prioridad', '2', '2026-02-15') then
    raise exception 'Falta la prioridad 2 (24 HORAS CON OPERACIONES)';
  end if;
end;
$$;
